# Generated by Django 5.0.6 on 2024-08-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_advance_payment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qualified',
            field=models.CharField(choices=[('Q', 'Quota'), ('N', 'Non quota'), ('0', 'Not Applicable')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='approval',
            field=models.CharField(choices=[('V', 'Verified'), ('R', 'Verficiation Failed'), ('P', 'Pending Verification'), ('U', 'Not Uploaded')], default='U', max_length=1),
        ),
    ]
