# Generated by Django 5.0.1 on 2024-05-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('rating', models.IntegerField()),
                ('last', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=3)),
                ('games', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unrated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WespaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(max_length=4)),
                ('rating', models.IntegerField()),
                ('games', models.IntegerField()),
                ('last', models.CharField(max_length=20)),
            ],
        ),
    ]
